# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='suggestions.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11suggestions.proto\"%\n\x12SuggestionsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\'\n\x10SuggestionsReply\x12\x13\n\x0bsuggestions\x18\x01 \x03(\x05\x32\x42\n\x0bSuggestions\x12\x33\n\x07Suggest\x12\x13.SuggestionsRequest\x1a\x11.SuggestionsReply\"\x00\x62\x06proto3')
)




_SUGGESTIONSREQUEST = _descriptor.Descriptor(
  name='SuggestionsRequest',
  full_name='SuggestionsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='SuggestionsRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=58,
)


_SUGGESTIONSREPLY = _descriptor.Descriptor(
  name='SuggestionsReply',
  full_name='SuggestionsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='suggestions', full_name='SuggestionsReply.suggestions', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['SuggestionsRequest'] = _SUGGESTIONSREQUEST
DESCRIPTOR.message_types_by_name['SuggestionsReply'] = _SUGGESTIONSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SuggestionsRequest = _reflection.GeneratedProtocolMessageType('SuggestionsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTIONSREQUEST,
  __module__ = 'suggestions_pb2'
  # @@protoc_insertion_point(class_scope:SuggestionsRequest)
  ))
_sym_db.RegisterMessage(SuggestionsRequest)

SuggestionsReply = _reflection.GeneratedProtocolMessageType('SuggestionsReply', (_message.Message,), dict(
  DESCRIPTOR = _SUGGESTIONSREPLY,
  __module__ = 'suggestions_pb2'
  # @@protoc_insertion_point(class_scope:SuggestionsReply)
  ))
_sym_db.RegisterMessage(SuggestionsReply)



_SUGGESTIONS = _descriptor.ServiceDescriptor(
  name='Suggestions',
  full_name='Suggestions',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=101,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='Suggest',
    full_name='Suggestions.Suggest',
    index=0,
    containing_service=None,
    input_type=_SUGGESTIONSREQUEST,
    output_type=_SUGGESTIONSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUGGESTIONS)

DESCRIPTOR.services_by_name['Suggestions'] = _SUGGESTIONS

# @@protoc_insertion_point(module_scope)
